### ISSUE TITLE
Annotations are broken in the newsfeed

### ISSUE THREAD

**Issue by frankrousseau** [cgwire/kitsu#1118]
**Context**

Studio name: Miyu
Kitsu version: 0.17.7
Production type: Feature

**Describe the bug**

The annotation system doesn't work in the newsfeed, in the only previews section.

**Comment by frankrousseau** [comment]
Fixed

**Comment by PeteDraper** [comment]
This still appears broken when annotating in the Notifications page. Using Chrome.
