### ISSUE TITLE
Unable to edit Production Setting

### ISSUE THREAD

**Issue by darkprince334455** [cgwire/kitsu#1634]
**Context**

Studio name: Monsta SDN BHD
Kitsu version: 0.20.9
Production type: TV Show

**Describe the bug**

Details in the production setting can't be changed or saved. Pressing save does nothing, and refreshing the page, auto set the start date and due date to today's date

**Screenshots**

![image](https://github.com/user-attachments/assets/210278c6-4ac1-4ec5-9c87-80a6338e43e4)

**Desktop (please complete the following information):**

- OS: [Windows 10 pro]
- Browser [Chrome]
- Version [131.0.6778.87 (Official Build) (64-bit)]

**Comment by NicoPennec** [comment]
Hi @darkprince334455
Sorry for the trouble. It was fixed last Friday (see https://github.com/cgwire/kitsu/pull/1632).
I just released Kitsu v0.20.10 containing the fix.

**Comment by darkprince334455** [comment]
> Hi @darkprince334455 Sorry for the trouble. It was fixed last Friday (see #1632). I just released Kitsu v0.20.10 containing the fix.

The issue still appears on my end even in version 0.20.10. The start and end date will state today's date, on save no prompt appears. The only different is in the console no error

![image](https://github.com/user-attachments/assets/87b610f7-47aa-4a07-b52d-3b9c53edb381)

**Comment by NicoPennec** [comment]
Date fields issue fixed on Kitsu v0.20.11
