### ISSUE TITLE
When a playlist on the fly is saved, the other playlists are not displayed anymore on the playlist page

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#516]
On a tv show, short and feature film.

When a playlist "on-the-fly" is saved (asset or shot, for client or studio), and then, when we go to the playlist page, only the "on-the-fly" playlists are displayed. 
A refresh of the page solved this issue.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
I still have the issue

![image](https://user-images.githubusercontent.com/42962633/91884085-b3d35b00-ec85-11ea-91ce-831aa4038223.png)
![image](https://user-images.githubusercontent.com/42962633/91884104-bdf55980-ec85-11ea-8cb2-ea5ec05db48a.png)

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?
