### ISSUE TITLE
After a certain number of lines, the drawing tool stops working

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#581]
on a tv show, short, feature film.

When we are in a task on full screen. It seems that we are limited to a number of lines on a single frame.
After some lines drawn the tools stop working.

**Comment by frankrousseau** [comment]
I'm not able to reproduce. Do you have a number of lines to give?

**Comment by ezraprakasa** [comment]
Maybe this related with this error, we can't move delete or edit text after move to another frame and back to the annotated frame.

![Kitsu Bug](https://user-images.githubusercontent.com/1551661/100822443-e4917f00-3484-11eb-8711-38c4e6c56d43.gif)

**Comment by frankrousseau** [comment]
Can you update your installation?

**Comment by frankrousseau** [comment]
I can reproduce the text bug. We'll see what can be done for this.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed, thanks

**Comment by ezraprakasa** [comment]
@frankrousseau

Sorry for reopen this issue, I still can't edit or move the line or text after changing frame and the only way to delete the line or text is using undo.

![kitsu-preview-error](https://user-images.githubusercontent.com/1551661/102565532-3afeee80-4110-11eb-9bb8-7c7876960ce4.gif)

Kitsu 0.12.33

**Comment by frankrousseau** [comment]
It doesn't happen every time. I have to find which cases lead to that bug.

**Comment by ezraprakasa** [comment]
> It doesn't happen every time. I have to find which cases lead to that bug.

Sorry for slow reply, just found out the problem exist on Google Chrome but not on Firefox and Opera

**Comment by frankrousseau** [comment]
Sorry but I can't reproduce it anymore even on Chrome. Do you a reproducible path for this?
