### ISSUE TITLE
When a production is freshly created, the task type page needs to be refreshed for every change.

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#679]
On a TVshow, short and feature film.

When we create a new production, with some assets and shots, and we add some tasks.
If we go to a task-type page, the filter doesn't work until we refresh the page.

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
I'm sorry, but the filter still doesn't work when the production is freshly created

**Comment by frankrousseau** [comment]
It should be fixed, can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks!
